# Generated by Django 2.1.3 on 2018-12-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userMail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(default='朱老师', max_length=16),
        ),
    ]
